# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.0.4

package:
  name: jsonasobj2
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jsonasobj2/jsonasobj2-${{ version }}.tar.gz
  sha256: f50b1668ef478004aa487b2d2d094c304e5cb6b79337809f4a1f2975cc7fbb4e

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pbr
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - hbreader
    - python >=${{ python_min }}

tests:
  - python:
      imports: jsonasobj2
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*

about:
  summary: JSON as python objects - version 2
  license: CC0-1.0
  license_file: license.txt
  homepage: https://github.com/hsolbrig/jsonasobj2

extra:
  recipe-maintainers:
    - bollwyvl
